$ComputerPublicIP = (Invoke-WebRequest -UseBasicParsing -uri "http://ifconfig.me/ip").Content
$Computerlocation = Invoke-RestMethod -Method Get -Uri "http://ip-api.com/json/$ComputerPublicIP"
$ComputerCountry = $Computerlocation.country

# Convert Country to Hex
if($Computerlocation.country -eq "Argentina"){$Location = "0xb"}
if($Computerlocation.country -eq "Australia"){$Location = "0xc"}
if($Computerlocation.country -eq "Austria"){$Location = "0xe"}
if($Computerlocation.country -eq "Belgium"){$Location = "0x15"}
if($Computerlocation.country -eq "Bosnia and Herzegovina"){$Location = "0x19"}
if($Computerlocation.country -eq "Brazil"){$Location = "0x20"}
if($Computerlocation.country -eq "Bulgaria"){$Location = "0x23"}
if($Computerlocation.country -eq "Canada"){$Location = "0x27"}
if($Computerlocation.country -eq "Cambodia"){$Location = "0x28"}
if($Computerlocation.country -eq "China"){$Location = "0x2d"}
if($Computerlocation.country -eq "Chile"){$Location = "0x2e"}
if($Computerlocation.country -eq "Colombia"){$Location = "0x33"}
if($Computerlocation.country -eq "Costa Rica"){$Location = "0x36"}
if($Computerlocation.country -eq "Cyprus"){$Location = "0x3b"}
if($Computerlocation.country -eq "Denmark"){$Location = "0x3d"}
if($Computerlocation.country -eq "Ecuador"){$Location = "0x42"}
if($Computerlocation.country -eq "Egypt"){$Location = "0x43"}
if($Computerlocation.country -eq "Ireland"){$Location = "0x44"}
if($Computerlocation.country -eq "Estonia"){$Location = "0x46"}
if($Computerlocation.country -eq "Czech Republic"){$Location = "0x4b"}
if($Computerlocation.country -eq "Finland"){$Location = "0x4d"}
if($Computerlocation.country -eq "France"){$Location = "0x54"}
if($Computerlocation.country -eq "Germany"){$Location = "0x5e"}
if($Computerlocation.country -eq "Greece"){$Location = "0x62"}
if($Computerlocation.country -eq "Hong Kong SAR"){$Location = "0x68"}
if($Computerlocation.country -eq "Honduras"){$Location = "0x6a"}
if($Computerlocation.country -eq "Croatia"){$Location = "0x6c"}
if($Computerlocation.country -eq "Hungary"){$Location = "0x6d"}
if($Computerlocation.country -eq "Iceland"){$Location = "0x6e"}
if($Computerlocation.country -eq "Indonesia"){$Location = "0x6f"}
if($Computerlocation.country -eq "India"){$Location = "0x71"}
if($Computerlocation.country -eq "Israel"){$Location = "0x75"}
if($Computerlocation.country -eq "Italy"){$Location = "0x76"}
if($Computerlocation.country -eq "Japan"){$Location = "0x7a"}
if($Computerlocation.country -eq "Korea"){$Location = "0x86"}
if($Computerlocation.country -eq "Kuwait"){$Location = "0x88"}
if($Computerlocation.country -eq "Latvia"){$Location = "0x8c"}
if($Computerlocation.country -eq "Lithuania"){$Location = "0x8d"}
if($Computerlocation.country -eq "Slovakia"){$Location = "0x8f"}
if($Computerlocation.country -eq "Liechtenstein"){$Location = "0x91"}
if($Computerlocation.country -eq "Luxembourg"){$Location = "0x93"}
if($Computerlocation.country -eq "Malta"){$Location = "0xa3"}
if($Computerlocation.country -eq "Mexico"){$Location = "0xa6"}
if($Computerlocation.country -eq "Malaysia"){$Location = "0xa7"}
if($Computerlocation.country -eq "Netherlands"){$Location = "0xb0"}
if($Computerlocation.country -eq "Norway"){$Location = "0xb1"}
if($Computerlocation.country -eq "New Zealand"){$Location = "0xb7"}
if($Computerlocation.country -eq "Paraguay"){$Location = "0xb9"}
if($Computerlocation.country -eq "Peru"){$Location = "0xbb"}
if($Computerlocation.country -eq "Poland"){$Location = "0xbf"}
if($Computerlocation.country -eq "Panama"){$Location = "0xc0"}
if($Computerlocation.country -eq "Portugal"){$Location = "0xc1"}
if($Computerlocation.country -eq "Romania"){$Location = "0xc8"}
if($Computerlocation.country -eq "Philippines"){$Location = "0xc9"}
if($Computerlocation.country -eq "Puerto Rico"){$Location = "0xca"}
if($Computerlocation.country -eq "Russia"){$Location = "0xcb"}
if($Computerlocation.country -eq "Saudi Arabia"){$Location = "0xcd"}
if($Computerlocation.country -eq "South Africa"){$Location = "0xd1"}
if($Computerlocation.country -eq "Slovenia"){$Location = "0xd4"}
if($Computerlocation.country -eq "Singapore"){$Location = "0xd7"}
if($Computerlocation.country -eq "Spain"){$Location = "0xd9"}
if($Computerlocation.country -eq "Sweden"){$Location = "0xdd"}
if($Computerlocation.country -eq "Switzerland"){$Location = "0xdf"}
if($Computerlocation.country -eq "United Arab Emirates"){$Location = "0xe0"}
if($Computerlocation.country -eq "Thailand"){$Location = "0xe3"}
if($Computerlocation.country -eq "Ukraine"){$Location = "0xf1"}
if($Computerlocation.country -eq "United Kingdom"){$Location = "0xf2"}
if($Computerlocation.country -eq "United States"){$Location = "0xf4"}
if($Computerlocation.country -eq "Uruguay"){$Location = "0xf6"}
if($Computerlocation.country -eq "Venezuela"){$Location = "0xf9"}
if($Computerlocation.country -eq "Serbia and Montenegro (Former)"){$Location = "0x10d"}
if($Computerlocation.country -eq "Montenegro"){$Location = "0x10e"}
if($Computerlocation.country -eq "Serbia"){$Location = "0x10f"}

#Set-WinHomelocation based on Location
Set-WinHomeLocation -GeoId $Location